/*******************************************************************************
  PROJETO: E-COMMERCE COMPLETO (MINI_EC)
  ESTRUTURA: CADASTROS, ESTOQUE, PEDIDOS, NOTAS E RASTREABILIDADE
  PADRONIZAÇÃO: VÍRGULAS À DIREITA E INTEGRIDADE REFERENCIAL
*******************************************************************************/

CREATE DATABASE IF NOT EXISTS MINI_EC;

USE MINI_EC;

-- =============================================================================
-- 1. CADASTROS INDEPENDENTES (TABELAS DE APOIO)
-- =============================================================================

CREATE TABLE USUARIOS 
(
      ID_USER       INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      NOME_USER     VARCHAR(50) NOT NULL,
      EMAIL_USER    VARCHAR(60) NOT NULL,
      SENHA         VARCHAR(32) NOT NULL,
      DATA_CADASTRO DATETIME NOT NULL,
      STATUS        ENUM('A', 'B'), -- A= ATIVO, B= BLOQUEADO
      CONSTRAINT UC_EMAIL UNIQUE (EMAIL_USER)
);

CREATE TABLE CATEGORIAS 
(
      ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      DESCRICAO    VARCHAR(50) NOT NULL
);

CREATE TABLE FABRICANTES 
(
      ID_FABRICANTE   INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      NOME_FABRICANTE VARCHAR(50) NOT NULL
);

CREATE TABLE UNIDADE_FEDERAL 
(
      COD_UF  TINYINT NOT NULL PRIMARY KEY,
      UF      CHAR(2) NOT NULL,
      NOME_UF VARCHAR(50) NOT NULL
);

CREATE TABLE CIDADES 
(
      ID_CIDADE   INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      NOME_CIDADE VARCHAR(70) NOT NULL,
      COD_MUN     CHAR(7) NOT NULL,
      COD_UF      TINYINT NOT NULL,
      CONSTRAINT FK_CID_UF FOREIGN KEY (COD_UF) REFERENCES UNIDADE_FEDERAL(COD_UF)
);


-- =============================================================================
-- 2. CATÁLOGO E INVENTÁRIO (PRODUTOS E ESTOQUE)
-- =============================================================================

CREATE TABLE PRODUTO 
(
      ID_PRODUTO    INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      DESCRICAO     VARCHAR(100) NOT NULL,
      ID_CATEGORIA  INT NOT NULL,
      ID_FABRICANTE INT NOT NULL,
      PRECO_CUSTO   DECIMAL(10, 2),
      PRECO_VENDA   DECIMAL(10, 2),
      CONSTRAINT FK_PROD_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
      CONSTRAINT FK_PROD_FAB FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTES(ID_FABRICANTE)
);

CREATE TABLE PRODUTO_CARACTER 
(
      ID_PRODUTO     INT NOT NULL,
      CARACTERISTICA VARCHAR(50) NOT NULL,
      VALOR          VARCHAR(50) NOT NULL,
      CONSTRAINT FK_CARAC_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE ESTOQUE 
(
      ID_PRODUTO        INT NOT NULL,
      ESTOQUE_TOTAL     INT NOT NULL,
      ESTOQUE_LIVRE     INT,
      ESTOQUE_RESERVADO INT,
      CONSTRAINT FK_ESTQ_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);


-- =============================================================================
-- 3. CLIENTES E PAGAMENTO
-- =============================================================================

CREATE TABLE CLIENTES 
(
      ID_CLIENTE    INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      NOME          VARCHAR(32) NOT NULL,
      SOBRENOME     VARCHAR(32) NOT NULL,
      EMAIL         VARCHAR(60) NOT NULL,
      SENHA         VARCHAR(32) NOT NULL,
      DATA_NASC     DATE NOT NULL,
      DATA_CADASTRO DATETIME NOT NULL,
      ULT_ACESSO    DATETIME,
      ULT_COMPRA    DATETIME,
      SITUACAO      ENUM('A', 'B') NOT NULL -- A= ATIVO, B= BLOQUEADO
);

CREATE TABLE CLIENTE_ENDERECO 
(
      ID_ENDERECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      ID_CLIENTE  INT NOT NULL,
      TIPO        ENUM('P', 'A') NOT NULL, -- P= PRINCIPAL, A= ALTERNATIVO
      ENDERECO    VARCHAR(60) NOT NULL,
      NUMERO      VARCHAR(10) NOT NULL,
      BAIRRO      VARCHAR(30) NOT NULL,
      CEP         VARCHAR(8) NOT NULL,
      ID_CIDADE   INT NOT NULL,
      CONSTRAINT FK_END_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
      CONSTRAINT FK_END_CID FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES(ID_CIDADE)
);

CREATE TABLE COND_PAGTO 
(
      ID_PAGTO  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      DESCRICAO VARCHAR(50) NOT NULL,
      TIPO      ENUM('C', 'D', 'B') NOT NULL -- C= CARTÃO, D= DÉBITO, B= BOLETO
);

CREATE TABLE COND_PAGTO_DET 
(
      ID_PAGTO   INT NOT NULL,
      PARCELA    INT NOT NULL,
      PERCENTUAL DECIMAL(10, 2) NOT NULL,
      DIAS       INT NOT NULL,
      CONSTRAINT FK_PAG_DET FOREIGN KEY (ID_PAGTO) REFERENCES COND_PAGTO(ID_PAGTO)
);


-- =============================================================================
-- 4. MOVIMENTAÇÃO: PEDIDOS E NOTAS FISCAIS
-- =============================================================================

CREATE TABLE PEDIDOS 
(
      NUM_PEDIDO       INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      ID_CLIENTE       INT NOT NULL,
      ID_ENDERECO      INT NOT NULL,
      ID_PAGTO         INT NOT NULL,
      TOTAL_PROD       DECIMAL(10, 2),
      TOTAL_FRETE      DECIMAL(10, 2),
      TOTAL_DESC       DECIMAL(10, 2),
      TOTAL_PEDIDO     DECIMAL(10, 2),
      DATA_PEDIDO      DATETIME NOT NULL,
      PREVISAO_ENTREGA DATE,
      EFETIVA_ENTREGA  DATE,
      STATUS_PED       ENUM('A', 'S', 'F', 'T', 'E'), -- A=AGUARD, S=SEPARAÇÃO, F=FATURADO, T=TRÂNSITO, E=ENTREGUE
      CONSTRAINT FK_PED_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
      CONSTRAINT FK_PED_END FOREIGN KEY (ID_ENDERECO) REFERENCES CLIENTE_ENDERECO(ID_ENDERECO),
      CONSTRAINT FK_PED_PAG FOREIGN KEY (ID_PAGTO) REFERENCES COND_PAGTO(ID_PAGTO)
);

CREATE TABLE PEDIDO_ITENS 
(
      NUM_PEDIDO INT NOT NULL,
      ID_PRODUTO INT NOT NULL,
      QTD        INT NOT NULL,
      VAL_UNIT   DECIMAL(10, 2) NOT NULL,
      DESCONTO   DECIMAL(10, 2) NOT NULL,
      TOTAL      DECIMAL(10, 2) NOT NULL,
      CONSTRAINT FK_ITENS_PED FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDOS(NUM_PEDIDO),
      CONSTRAINT FK_ITENS_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE NOTA_FISCAL 
(
      NUM_NOTA    INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      NUM_PED_REF INT NOT NULL,
      ID_CLIENTE  INT NOT NULL,
      ID_ENDERECO INT NOT NULL,
      ID_PAGTO    INT NOT NULL,
      TOTAL_PROD  DECIMAL(10, 2),
      TOTAL_FRETE DECIMAL(10, 2),
      TOTAL_DESC  DECIMAL(10, 2),
      TOTAL_NF    DECIMAL(10, 2),
      DATA_NF     DATETIME NOT NULL,
      STATUS_NF   ENUM('N', 'C', 'D'), -- N=NORMAL, C=CANCELADA, D=DEVOLVIDA
      ID_USER     INT,
      CONSTRAINT FK_NF_PED FOREIGN KEY (NUM_PED_REF) REFERENCES PEDIDOS(NUM_PEDIDO),
      CONSTRAINT FK_NF_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
      CONSTRAINT FK_NF_END FOREIGN KEY (ID_ENDERECO) REFERENCES CLIENTE_ENDERECO(ID_ENDERECO)
);


-- =============================================================================
-- 5. RASTREABILIDADE E SESSÃO
-- =============================================================================

CREATE TABLE CARRINHO_COMPRAS 
(
      SESSAO          VARCHAR(32) NOT NULL,
      ID_PRODUTO      INT NOT NULL,
      QTD             INT NOT NULL, 
      VAL_UNIT        DECIMAL(10, 2) NOT NULL,
      DESCONTO        DECIMAL(10, 2) NOT NULL, 
      TOTAL           DECIMAL(10, 2) NOT NULL,
      DATA_HORA_SESSA DATETIME NOT NULL,
      INDEX IX_SESSAO (SESSAO),
      CONSTRAINT FK_CAR_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE RASTREABILIDADE 
(
      NUM_PEDIDO INT NOT NULL,
      STATUS_PED CHAR(1) NOT NULL,
      DATA_HORA  DATETIME NOT NULL,
      ID_USER    INT,
      CONSTRAINT FK_RAST_PED FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDOS(NUM_PEDIDO)
);