/*******************************************************************************
  SCRIPT DE ESTUDO: CONTROLE DE ESTOQUE AVANÇADO (TRANSAÇÕES E LOTES)
  PADRONIZAÇÃO: VÍRGULAS À DIREITA E INTEGRIDADE REFERENCIAL.
*******************************************************************************/

USE CURSO;

-- =============================================================================
-- 1. ESTRUTURA DE TABELAS (DDL)
-- =============================================================================

CREATE TABLE ZTOK (
      COD_MAT VARCHAR(20) PRIMARY KEY NOT NULL,
      SALDO   DECIMAL(10,2) NOT NULL
);

CREATE TABLE ZTOK_LOTE (
      COD_MAT INT,
      LOTE    VARCHAR(15) NOT NULL,
      SALDO   DECIMAL(10,2) NULL,
      FOREIGN KEY (COD_MAT) REFERENCES MATERIAL(COD_MAT),
      PRIMARY KEY (COD_MAT, LOTE)
);

CREATE TABLE MOV_ZTOK (
      TRANSACAO  INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
      MOV        VARCHAR(1) NOT NULL,
      COD_MAT    INT NOT NULL,
      LOTE       VARCHAR(15) NOT NULL,
      QTD        INT NOT NULL,
      USUARIO    VARCHAR(30) NOT NULL,
      DT_HOR_MOV DATETIME NOT NULL,
      FOREIGN KEY (COD_MAT) REFERENCES MATERIAL(COD_MAT)
);

CREATE UNIQUE INDEX IX_ZTOK1 ON ZTOK(COD_MAT);


-- =============================================================================
-- 2. PROCEDURE DE ATUALIZAÇÃO DE ESTOQUE
-- CONSOLIDA ENTRADAS, SAÍDAS E CRIAÇÃO DINÂMICA DE SALDOS.
-- =============================================================================

DELIMITER //

CREATE PROCEDURE PROC_ATUALIZA_ESTOQUE (
      IN TIPO_MOV  VARCHAR(1),
      IN P_COD_MAT VARCHAR(50),
      IN P_LOTE    VARCHAR(15),
      IN P_QTD_MOV DECIMAL(10,2)
)
MAIN: BEGIN
      -- DECLARAÇÃO DE VARIÁVEIS DE CONTROLE E DIAGNÓSTICO
      DECLARE COD_ERRO      CHAR(5) DEFAULT '00000';
      DECLARE MSG           TEXT;
      DECLARE ROWS_AFFECTED INT;
      DECLARE RESULT        TEXT;
      DECLARE SALDO_ESTOQUE DECIMAL(10,2) DEFAULT 0;
      DECLARE SALDO_LOTE    DECIMAL(10,2) DEFAULT 0;
      DECLARE REG_Z         INT DEFAULT 0;
      DECLARE REG_ZL        INT DEFAULT 0;
      
      -- TRATAMENTO DE EXCEÇÕES COM DIAGNÓSTICO
      DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
      BEGIN
            GET DIAGNOSTICS CONDITION 1
            COD_ERRO = RETURNED_SQLSTATE, MSG = MESSAGE_TEXT;
      END;
    
      -- VALIDAÇÕES PRELIMINARES (RESULTADO IMEDIATO EM CASO DE ERRO)
      IF TIPO_MOV NOT IN ('E', 'S') OR P_QTD_MOV < 1 THEN
            SELECT 'OPERAÇÃO INVÁLIDA OU VALOR MENOR QUE 1' AS ERRO;
            LEAVE MAIN;
      END IF;

      IF (SELECT COUNT(*) FROM MATERIAL WHERE COD_MAT = P_COD_MAT) = 0 THEN
            SELECT 'MATERIAL NÃO EXISTE!' AS ERRO;
            LEAVE MAIN;
      END IF;
        
      -- CAPTURA SALDOS ATUAIS PARA VALIDAÇÃO DE ESTOQUE NEGATIVO
      SELECT SALDO INTO SALDO_ESTOQUE FROM ZTOK WHERE COD_MAT = P_COD_MAT;
      SELECT SALDO INTO SALDO_LOTE FROM ZTOK_LOTE WHERE COD_MAT = P_COD_MAT AND LOTE = P_LOTE;

      IF TIPO_MOV = 'S' AND (SALDO_ESTOQUE < P_QTD_MOV OR SALDO_LOTE < P_QTD_MOV) THEN
            SELECT 'ESTOQUE INSUFICIENTE NO GLOBAL OU LOTE, OPERAÇÃO CANCELADA' AS ERRO;
            LEAVE MAIN;
      END IF;
        
      -- INÍCIO DA TRANSAÇÃO PARA GARANTIR ACID
      START TRANSACTION;

      -- VERIFICA EXISTÊNCIA DE REGISTROS PARA DECIDIR ENTRE INSERT OU UPDATE
      SELECT COUNT(*) INTO REG_Z FROM ZTOK WHERE COD_MAT = P_COD_MAT;
      SELECT COUNT(*) INTO REG_ZL FROM ZTOK_LOTE WHERE COD_MAT = P_COD_MAT AND LOTE = P_LOTE;
        
      -- LÓGICA DE SAÍDA (S)
      IF (TIPO_MOV = 'S') THEN
            UPDATE ZTOK SET SALDO = SALDO - P_QTD_MOV WHERE COD_MAT = P_COD_MAT;
            UPDATE ZTOK_LOTE SET SALDO = SALDO - P_QTD_MOV WHERE COD_MAT = P_COD_MAT AND LOTE = P_LOTE;
            
            INSERT INTO MOV_ZTOK (MOV, COD_MAT, LOTE, QTD, USUARIO, DT_HOR_MOV)
            VALUES (TIPO_MOV, P_COD_MAT, P_LOTE, P_QTD_MOV, USER(), NOW());
      
      -- LÓGICA DE ENTRADA (E) - CASO JÁ EXISTA REGISTRO
      ELSEIF (TIPO_MOV = 'E' AND REG_Z = 1) THEN
            UPDATE ZTOK SET SALDO = SALDO + P_QTD_MOV WHERE COD_MAT = P_COD_MAT;
            
            IF REG_ZL = 1 THEN
                  UPDATE ZTOK_LOTE SET SALDO = SALDO + P_QTD_MOV WHERE COD_MAT = P_COD_MAT AND LOTE = P_LOTE;
            ELSE
                  INSERT INTO ZTOK_LOTE (COD_MAT, LOTE, SALDO) VALUES (P_COD_MAT, P_LOTE, P_QTD_MOV);
            END IF;

            INSERT INTO MOV_ZTOK (MOV, COD_MAT, LOTE, QTD, USUARIO, DT_HOR_MOV)
            VALUES (TIPO_MOV, P_COD_MAT, P_LOTE, P_QTD_MOV, USER(), NOW());

      -- LÓGICA DE ENTRADA (E) - NOVO MATERIAL
      ELSEIF (TIPO_MOV = 'E' AND REG_Z = 0) THEN
            INSERT INTO ZTOK (COD_MAT, SALDO) VALUES (P_COD_MAT, P_QTD_MOV);
            INSERT INTO ZTOK_LOTE (COD_MAT, LOTE, SALDO) VALUES (P_COD_MAT, P_LOTE, P_QTD_MOV);
            INSERT INTO MOV_ZTOK (MOV, COD_MAT, LOTE, QTD, USUARIO, DT_HOR_MOV)
            VALUES (TIPO_MOV, P_COD_MAT, P_LOTE, P_QTD_MOV, USER(), NOW());
      END IF;
        
      -- AVALIAÇÃO DE RESULTADO E FINALIZAÇÃO DA TRANSAÇÃO
      IF COD_ERRO = '00000' THEN
            GET DIAGNOSTICS ROWS_AFFECTED = ROW_COUNT;
            SET RESULT = CONCAT('ATUALIZAÇÃO COM SUCESSO. LINHAS AFETADAS: ', ROWS_AFFECTED);
            COMMIT;
      ELSE
            SET RESULT = CONCAT('ERRO NA ATUALIZAÇÃO. CÓDIGO: ', COD_ERRO, ' | MSG: ', MSG);
            ROLLBACK;
      END IF;

      SELECT RESULT AS STATUS_PROCESSAMENTO;
        
END //

DELIMITER ;


-- =============================================================================
-- 3. EXECUÇÃO E TESTE DO RETORNO
-- =============================================================================

-- TESTANDO UMA SAÍDA
CALL PROC_ATUALIZA_ESTOQUE('S', '1', 'DEF', 5.00);

-- CONFERÊNCIA DE RESULTADOS
SELECT * FROM ZTOK;
SELECT * FROM ZTOK_LOTE;
SELECT * FROM MOV_ZTOK;
SELECT * FROM MATERIAL;