/*******************************************************************************
  SCRIPT DE ESTUDO: STORED FUNCTIONS (FUNÇÕES ARMAZENADAS)
  PADRONIZAÇÃO: VÍRGULAS À DIREITA E REUTILIZAÇÃO DE LÓGICA.
*******************************************************************************/

USE CURSO;

-- =============================================================================
-- 1. FUNÇÕES ARITMÉTICAS SIMPLES
-- EXPLICAÇÃO: RECEBE PARÂMETROS E RETORNA O RESULTADO DA MULTIPLICAÇÃO.
-- =============================================================================

DELIMITER //
CREATE FUNCTION FN_TESTE (A DECIMAL(10,2), B INT)
RETURNS INT
DETERMINISTIC
BEGIN
      RETURN A * B;
END //
DELIMITER ;

-- RETORNA O RESULTADO DO CÁLCULO
SELECT FN_TESTE(12.5, 3) AS RESULTADO;


-- =============================================================================
-- 2. TRATAMENTO DE TEXTO (INITCAP E BOAS VINDAS)
-- GERA UM RETORNO PADRONIZADO COM A PRIMEIRA LETRA EM MAIÚSCULA.
-- =============================================================================

DELIMITER //
CREATE FUNCTION FN_INITCAP (NOME VARCHAR(50))
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
      RETURN CONCAT(UPPER(SUBSTRING(NOME, 1, 1)), LOWER(SUBSTRING(NOME, 2, 50)));
END //

CREATE FUNCTION FN_BOAS_VINDAS (USUARIO VARCHAR(50))
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
      RETURN CONCAT('OLÁ ', USUARIO, ', SEJA BEM VINDO!');
END //
DELIMITER ;

-- TESTANDO O RESULTADO DAS FUNÇÕES DE TEXTO
SELECT FN_INITCAP('mysql tutorial') AS NOME_FORMATADO;
SELECT FN_BOAS_VINDAS(USER()) AS MENSAGEM;


-- =============================================================================
-- 3. LÓGICA COM CONSULTAS (DECLARAÇÃO DE VARIÁVEIS E INTO)
-- RETORNA O RESULTADO DE UMA CONTAGEM BASEADA EM UM PARÂMETRO EXTERNO.
-- =============================================================================

USE SAKILA;

DELIMITER //
CREATE FUNCTION FN_FILMES_ATOR(ID_ATOR INT)
RETURNS INT
READS SQL DATA
BEGIN
      DECLARE QTD INT;
      SELECT COUNT(*) INTO QTD 
      FROM FILM_ACTOR 
      WHERE ACTOR_ID = ID_ATOR;
      RETURN QTD;
END //
DELIMITER ;

-- RETORNA A QUANTIDADE DE FILMES DO ATOR 1
SELECT FN_FILMES_ATOR(1) AS TOTAL_FILMES;


-- =============================================================================
-- 4. CÁLCULOS COMPLEXOS (MÉDIA DE NOTAS E AUMENTO)
-- UTILIZA VARIÁVEIS LOCAIS PARA PROCESSAR O RESULTADO FINAL.
-- =============================================================================

USE CURSO;

DELIMITER //
CREATE FUNCTION FN_MEDIA (NOME_ALUNO VARCHAR(10))
RETURNS FLOAT
READS SQL DATA
BEGIN
      DECLARE N1, N2, N3, N4 INT;
      DECLARE MED FLOAT;
      
      SELECT NOTA1, NOTA2, NOTA3, NOTA4 INTO N1, N2, N3, N4 
      FROM AVALIACAO WHERE ALUNO = NOME_ALUNO;
      
      SET MED = (N1 + N2 + N3 + N4) / 4;
      RETURN MED;
END //

-- CORREÇÃO: RETORNO DECIMAL PARA SUPORTAR O RESULTADO DO SALÁRIO
CREATE FUNCTION FN_SIMULA_AUMENTO(SALARIO DECIMAL(10,2), PCT DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
      RETURN SALARIO + (SALARIO * PCT / 100);
END //
DELIMITER ;

-- TESTANDO OS RESULTADOS
SELECT FN_MEDIA('PAUL') AS MEDIA_FINAL;
SELECT FN_SIMULA_AUMENTO(1550.70, 7.8) AS NOVO_SALARIO;


-- =============================================================================
-- 5. PERFORMANCE E ÍNDICES (FUNÇÕES COM SENSO)
-- OTIMIZA O RESULTADO DE BUSCAS GEOGRÁFICAS.
-- =============================================================================

DELIMITER //
CREATE FUNCTION FN_CIDADES(P_UF VARCHAR(2), P_ANO INT)
RETURNS INT
READS SQL DATA
BEGIN
      DECLARE QTD INT;
      SELECT COUNT(*) INTO QTD
      FROM SENSO 
      WHERE COD_UF = P_UF AND ANO = P_ANO;
      RETURN QTD;
END //
DELIMITER ;

-- CRIAÇÃO DE ÍNDICE PARA ACELERAR O RESULTADO DA FUNÇÃO
CREATE INDEX IX_SENSO_UF_ANO ON SENSO(COD_UF, ANO);

-- RETORNA O NÚMERO DE CIDADES POR ESTADO USANDO A FUNÇÃO
SELECT DISTINCT ESTADO, FN_CIDADES(COD_UF, 2024) 
AS TOTAL_CIDADES
FROM SENSO
WHERE ANO = 2024;