/*******************************************************************************
  SCRIPT DE ESTUDO: VIEWS (TABELAS VIRTUAIS) E UNIÃO DE DADOS
  PADRONIZAÇÃO: VÍRGULAS À DIREITA E ABSTRAÇÃO DE CONSULTAS COMPLEXAS.
*******************************************************************************/

USE SAKILA;

-- =============================================================================
-- 1. CRIAÇÃO DE VIEW COM MÚLTIPLOS JOINS
-- ABSTRAI A COMPLEXIDADE DE RELACIONAR ATORES A FILMES EM UMA ÚNICA ESTRUTURA.
-- =============================================================================

CREATE OR REPLACE VIEW V_ATOR_FILM AS
SELECT A.FIRST_NAME,
       C.TITLE,
       C.LENGTH AS DURACAO
FROM ACTOR AS A
INNER JOIN FILM_ACTOR AS B 
	ON A.ACTOR_ID = B.ACTOR_ID
INNER JOIN FILM AS C 
	ON B.FILM_ID = C.FILM_ID;

-- CONSULTA O RESULTADO DIRETAMENTE PELA VIEW
SELECT * FROM V_ATOR_FILM WHERE TITLE = 'GOODFELLAS SALUTE';


-- =============================================================================
-- 2. VIEWS SOBRE VIEWS (ANINHAMENTO E AGREGAÇÃO)
-- CALCULA O TOTAL DE MINUTOS E HORAS POR ATOR USANDO A VIEW ANTERIOR.
-- =============================================================================

CREATE OR REPLACE VIEW V_ATOR_FILM_HORAS AS
SELECT A.FIRST_NAME,
       SUM(A.DURACAO) AS MINUTOS,
       SUM(A.DURACAO) / 60 AS HORAS
FROM V_ATOR_FILM AS A
GROUP BY A.FIRST_NAME
ORDER BY 2 DESC;

-- LISTA DE FILMES CONCATENADOS POR ATOR
CREATE OR REPLACE VIEW V_ATOR_FILM_CONCAT AS
SELECT A.FIRST_NAME,
       GROUP_CONCAT(A.TITLE SEPARATOR ', ') AS FILMES
FROM V_ATOR_FILM AS A
GROUP BY A.FIRST_NAME;


-- =============================================================================
-- 3. VIEWS PARA UNIFICAÇÃO DE TABELAS PARTICIONADAS (UNION ALL)
-- IDEAL PARA UNIR DADOS QUE ESTÃO EM TABELAS DIFERENTES POR REGRAS DE NEGÓCIO.
-- =============================================================================

-- CRIAÇÃO DAS TABELAS DE FORNECEDORES COM CONSTRAINTS DE RANGE
CREATE TABLE FORNEC1 
(
      ID_FORNEC INT NOT NULL PRIMARY KEY,
      FORNEC VARCHAR(50) NOT NULL,
      CONSTRAINT CHK_F1 CHECK(ID_FORNEC BETWEEN 1 AND 150)
);

CREATE TABLE FORNEC2 
(
      ID_FORNEC INT NOT NULL PRIMARY KEY,
      FORNEC VARCHAR(50) NOT NULL,
      CONSTRAINT CHK_F2 CHECK(ID_FORNEC BETWEEN 151 AND 300)
);

CREATE TABLE FORNEC3 
(
      ID_FORNEC INT NOT NULL PRIMARY KEY,
      FORNEC VARCHAR(50) NOT NULL,
      CONSTRAINT CHK_F3 CHECK(ID_FORNEC BETWEEN 301 AND 450)
);

CREATE TABLE FORNEC4 
(
      ID_FORNEC INT NOT NULL PRIMARY KEY,
      FORNEC VARCHAR(50) NOT NULL,
      CONSTRAINT CHK_F4 CHECK(ID_FORNEC BETWEEN 451 AND 600)
);

-- INSERÇÃO DE DADOS PARA TESTE DO RESULTADO UNIFICADO
INSERT INTO FORNEC1 VALUES ('150', 'CALIFORNIACORP'), ('5', 'BRAZILIALTD');
INSERT INTO FORNEC2 VALUES ('231', 'FAREAST'), ('280', 'NZ');
INSERT INTO FORNEC3 VALUES ('321', 'EUROGROUP'), ('442', 'UKARCHIP');
INSERT INTO FORNEC4 VALUES ('475', 'INDIA'), ('521', 'AFRIQUE');

-- CRIAÇÃO DA VIEW QUE UNIFICA OS RESULTADOS DAS QUATRO TABELAS
CREATE OR REPLACE VIEW V_FORNEC_GERAL AS
SELECT 'F1' AS ORIGEM, ID_FORNEC, FORNEC FROM FORNEC1
UNION ALL
SELECT 'F2' AS ORIGEM, ID_FORNEC, FORNEC FROM FORNEC2
UNION ALL
SELECT 'F3' AS ORIGEM, ID_FORNEC, FORNEC FROM FORNEC3
UNION ALL
SELECT 'F4' AS ORIGEM, ID_FORNEC, FORNEC FROM FORNEC4;

-- RETORNO COMPLETO DOS FORNECEDORES COMO SE FOSSEM UMA ÚNICA TABELA
SELECT * FROM V_FORNEC_GERAL ORDER BY ID_FORNEC;