/*******************************************************************************
  SCRIPT DE ESTUDO: FUNÇÕES DE AGREGAÇÃO, ESTATÍSTICA E AGRUPAMENTOS
  PADRONIZAÇÃO: MÉTRICAS, SUBQUERIES E ANÁLISE DE DISPERSÃO.
*******************************************************************************/

USE CURSO;

-- 1. EXPLORAÇÃO INICIAL PARA VERIFICAÇÃO DO RESULTADO DOS DADOS
SELECT * FROM SENSO;

-- =============================================================================
-- 2. MÉDIAS DE POPULAÇÃO (AVG)
-- =============================================================================

-- GERA O RETORNO DA MÉDIA POPULACIONAL GLOBAL DE 2014
SELECT AVG(POPULACAO) AS MEDIA 
FROM SENSO
WHERE ANO = '2014';

-- RETORNA A MÉDIA POR ESTADO ORGANIZADA PELO MAIOR RESULTADO
SELECT ESTADO, 
    AVG(POPULACAO)
FROM SENSO
WHERE ANO = '2014'
GROUP BY ESTADO
ORDER BY 2 DESC;

-- RESULTADO DA MÉDIA POR UF UTILIZANDO JUNÇÃO DE TABELAS
SELECT  A.COD_UF, 
        B.SIGLA_UF, 
        AVG(A.POPULACAO) AS MEDIA
FROM SENSO AS A 
INNER JOIN UF AS B ON A.COD_UF = B.COD_UF
WHERE A.ANO = '2014'
GROUP BY A.COD_UF, 
         B.SIGLA_UF
ORDER BY 3 DESC;

-- RETORNA O RESULTADO MÉDIO AGRUPADO POR REGIÃO GEOGRÁFICA
SELECT  A.REGIAO, 
        AVG(A.POPULACAO) AS MEDIA
FROM SENSO AS A
WHERE ANO = '2014'
GROUP BY A.REGIAO;

-- =============================================================================
-- 3. VALORES MÍNIMOS (MIN)
-- =============================================================================

-- BUSCA O MENOR VALOR POPULACIONAL PARA RETORNO SIMPLIFICADO
SELECT MIN(A.POPULACAO) 
FROM SENSO AS A
WHERE ANO = '2014';

-- GERA O RESULTADO DO MÍNIMO POPULACIONAL POR UNIDADE FEDERATIVA
SELECT  A.ESTADO, 
        MIN(A.POPULACAO) 
FROM SENSO AS A
WHERE ANO = '2014'
GROUP BY A.ESTADO;

-- =============================================================================
-- 4. VALORES MÁXIMOS (MAX)
-- =============================================================================

-- RETORNA O MAIOR VALOR ENCONTRADO NO SENSO DE 2014
SELECT MAX(A.POPULACAO) 
FROM SENSO AS A
WHERE A.ANO = '2014';

-- EXIBE O RESULTADO DO MUNICÍPIO MAIS POPULOSO POR ESTADO
SELECT  A.ESTADO, 
        MAX(A.POPULACAO) 
FROM SENSO AS A
WHERE A.ANO = '2014'
GROUP BY A.ESTADO
ORDER BY 2 DESC;

-- =============================================================================
-- 5. SOMAS E TOTAIS (SUM)
-- =============================================================================

-- SOMA A POPULAÇÃO TOTAL POR SIGLA PARA RETORNO DO MONTANTE ESTADUAL
SELECT B.SIGLA_UF, 
       SUM(A.POPULACAO) AS TOTAL_POP
FROM SENSO AS A
INNER JOIN UF AS B ON A.COD_UF = B.COD_UF
WHERE A.ANO = '2014'
GROUP BY B.SIGLA_UF
ORDER BY 2;

-- =============================================================================
-- 6. CONTAGENS (COUNT)
-- =============================================================================

-- RETORNA A QUANTIDADE TOTAL DE REGISTROS DO ANO ESPECIFICADO
SELECT COUNT(*) 
FROM SENSO AS A 
WHERE A.ANO = '2014';

-- GERA O RESULTADO DA QUANTIDADE DE CIDADES POR ANO DE SENSO
SELECT A.ANO, 
       COUNT(*) AS QTD_CIDADES 
FROM SENSO AS A 
GROUP BY A.ANO;

-- COMPARAÇÃO ENTRE CONTAGEM ÚNICA E TOTAL PARA RETORNO DE DIVERSIDADE
SELECT COUNT(DISTINCT COD_UF) FROM SENSO;
SELECT COUNT(COD_UF) FROM SENSO;

-- =============================================================================
-- 7. RESUMOS AGRUPADOS E ROLLUP
-- =============================================================================

-- CONSOLIDA TODAS AS MÉTRICAS EM UM ÚNICO RESULTADO DE RETORNO
SELECT AVG(A.POPULACAO) AS MEDIA_POP, 
       MIN(A.POPULACAO) AS MINIMO_POP, 
       MAX(A.POPULACAO) AS MAXIMO_POP, 
       SUM(A.POPULACAO) AS SOMA_POP, 
       COUNT(*)         AS QTD_CIDADES
FROM SENSO AS A
WHERE ANO = '2014';

-- RESULTADO POR ESTADO COM ACRÉSCIMO DO TOTAL GERAL (ROLLUP)
SELECT  IFNULL(A.ESTADO, 'TOTAL BRASIL') AS ESTADO , 
	    COUNT(*) AS QTD_MUNICIPIOS
FROM SENSO AS A 
WHERE A.ANO = '2014'
GROUP BY A.ESTADO WITH ROLLUP;

-- =============================================================================
-- 8. SUBQUERIES (DESTAQUES POR ESTADO)
-- =============================================================================

-- UTILIZA SUBQUERY PARA IDENTIFICAR O MUNICÍPIO QUE GERA O RESULTADO MÁXIMO
SELECT A.ESTADO, 
       A.NOME_MUN, 
       A.POPULACAO
FROM (SELECT 
          B.ESTADO, 
          MAX(POPULACAO) AS POPULACAO 
    FROM SENSO AS B
    WHERE ANO = '2014'
    GROUP BY B.ESTADO
) AS B
JOIN 
    SENSO AS A ON A.ESTADO = B.ESTADO 
    AND A.POPULACAO = B.POPULACAO
WHERE A.ANO = '2014'
ORDER BY A.POPULACAO DESC;

-- =============================================================================
-- 9. ESTATÍSTICAS DE DISPERSÃO E CRESCIMENTO
-- =============================================================================

-- CALCULA O DESVIO PADRÃO PARA RETORNO DA VARIAÇÃO POPULACIONAL
SELECT STDDEV(A.POPULACAO) FROM SENSO AS A WHERE A.ANO = '2014';

-- COMPARA O CRESCIMENTO ENTRE PERÍODOS PARA RETORNO PERCENTUAL POR MUNICÍPIO
SELECT  A.NOME_MUN, A.POPULACAO AS SENSO_2010, 
        B.POPULACAO AS SENSO_2014, 
        ((B.POPULACAO - A.POPULACAO) / A.POPULACAO) * 100 
        AS CRESCIMENTO_PERCENTUAL
FROM SENSO AS A 
INNER JOIN SENSO AS B ON A.COD_MUN = B.COD_MUN
WHERE A.ANO = '2010' 
    AND B.ANO = '2014';

-- CALCULA A VARIANÇA PARA ANÁLISE DO RESULTADO DE DISPERSÃO DOS DADOS
SELECT VAR_POP(POPULACAO) FROM SENSO WHERE ANO = '2014';

-- =============================================================================
-- BANCO DE DADOS: WORLD (AGREGAÇÃO DE LISTAS)
-- =============================================================================
USE WORLD;

-- GERA UMA LISTA AGREGADA PARA RETORNO DE POPULAÇÕES POR CONTINENTE
SELECT CONTINENT, 
GROUP_CONCAT(DISTINCT POPULATION ORDER BY POPULATION DESC SEPARATOR ';') AS GRUPO 
FROM COUNTRY 
GROUP BY CONTINENT;

-- GERA UMA LISTA DE REGIÕES PARA RETORNO EM FORMATO DE TEXTO ÚNICO
SELECT CONTINENT, 
GROUP_CONCAT(DISTINCT REGION ORDER BY REGION DESC SEPARATOR ';') AS REGIAO 
FROM COUNTRY 
GROUP BY CONTINENT;